import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import OrderList from "@/components/pages-components/OrderList/OrderList";

export default function Customers() {
  return (
    <>
      <Head>
        <title>Order List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <OrderList />
      </div>
    </>
  );
}

Customers.getLayout = (pageProps) => (
  <MainLayout>
    <Customers {...pageProps} />
  </MainLayout>
);
