import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/Home.module.css";
import CustomerDetail from "@/components/common/CustomerDetail";
import CustomersList from "@/components/pages-components/foods/CustomersList";

export default function CustomerDetail() {
  return (
    <>
      <Head>
        <title>Customer List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CustomersList />
      </div>
    </>
  );
}

CustomersList.getLayout = (pageProps) => (
  <MainLayout>
    <CustomersList {...pageProps} />
  </MainLayout>
);
