import Head from "next/head";
// import CustomersList from "@/components/pagesComponents/customers/CustomersList";
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/Home.module.css";
import CustomerDetail from "@/components/common/layouts/CustomerDetail";

export default function Customers() {
  return (
    <>
      <Head>
        <title>Cutomers List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CustomerDetail />
      </div>
    </>
  );
}

CustomerDetail.getLayout = (pageProps) => (
  <MainLayout>
    <CustomerDetail {...pageProps} />
  </MainLayout>
);
