import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import ReviewsTable from "@/components/pages-components/reviews/ReviewsTable";

export default function Review() {
  return (
    <>
      <Head>
        <title>CustomerDetailList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Review />
      </div>
    </>
  );
}

Review.getLayout = (pageProps) => (
  <MainLayout>
    <ReviewsTable {...pageProps} />
  </MainLayout>
);
