import Head from "next/head";
import { useEffect, useState } from "react";
import MainLayout from "@/components/common/layouts/MainLayout";
import { TextField, Button, Box, Typography } from "@mui/material";
import { useRouter } from "next/router";
import FoodsData from "@/components/pages-components/foods/FoodsData";
export default function FoodEdit() {
  const router = useRouter();
  const [foundFood, setFoundFood] = useState(null);

  useEffect(() => {
    if (router.query.id) {
      const foodItem = FoodsData.find((item) => item.id === router.query.id);
      setFoundFood(foodItem);
    }
    [router.query.id];
  });
  return (
    <>
      <Head>
        <title>Orders List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
FoodEdit.getLayout = (pageProps) => (
  <MainLayout>
    <FoodEdit {...pageProps} />
  </MainLayout>
);
